version: 1.0.{build}
build_script:
- ps: ./build.ps1 -Target Package
test: off
deploy:
  provider: NuGet
  api_key:
    secure: e1D6p5+bkcxTSQ8tyfrQMyLJbZEHRIV6Obt2q1Qm+28+/LtSzSwSFUpgdATHK91A
  skip_symbols: false
  artifact: /.*\.nupkg/
