version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: ./build.ps1 -Target Package
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: e1D6p5+bkcxTSQ8tyfrQMyLJbZEHRIV6Obt2q1Qm+28+/LtSzSwSFUpgdATHK91A
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
